[package]
name = "lumin/net"
description = "A simple and lightweight networking library."
version = "0.5.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
debugger = "lumin/debugger@0.4.0"
