name: Event

on:
  issues:
    types: [opened]

jobs:
  send:
    name: Open Thread on Discord
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.0

      - name: Send webhook
        env:
          WEBHOOK_URL: ${{ secrets.EVENT_WEBHOOK_URL }}
        run: |
          PROJECT="${{ github.repository }}"
          EVENT_URL="${{ github.event.issue.html_url }}"
          EVENT_TITLE="${{ github.event.issue.title }}"

          lune run .lune/discord.luau "$WEBHOOK_URL" "event" "$PROJECT" "$EVENT_TITLE" "$EVENT_URL"
